### ISSUE TITLE
Converting text that starts with URL fails

### ISSUE THREAD

**Issue by matejzero** [bebraw/pypandoc#136]
I'm converting some text from textile to markdown and I have a case, where text begins with an URL and text follows.

Example:
```
text="http://www.example.com/page/\r\nSome text that follows"
converted = pypandoc.convert(text, 'markdown_strict', format='textile')
print(converted)
```

This fails with:
```
Traceback (most recent call last):
  File "issue_attachment_replace.py", line 22, in <module>
    converted = pypandoc.convert(text, 'markdown_strict', format='textile')
  File "/usr/local/lib/python3.5/dist-packages/pypandoc/__init__.py", line 69, in convert
    outputfile=outputfile, filters=filters)
  File "/usr/local/lib/python3.5/dist-packages/pypandoc/__init__.py", line 325, in _convert_input
    'Pandoc died with exitcode "%s" during conversion: %s' % (p.returncode, stderr)
RuntimeError: Pandoc died with exitcode "1" during conversion: b'pandoc: http://www.example.com/page/\r\nSome text that follows: openFile: does not exist (No such file or directory)\n'
```

Looking at the code, I think the problem is `_identify_path`function (https://github.com/bebraw/pypandoc/blob/master/pypandoc/__init__.py#L159).

We should somehow check if the URL is really an URL, but I have no idea how to make that cleanly and cover all cases. We could probably look for new line characters, but that won't work if we have `http://www.example.com/ - some text`. 

On the other hand, that's really an obscure case, but I think it's good to let you know.

**Comment by janschulz** [comment]
That looks like exactly the use case why we added `pandoc.convert_text(...)`. 

```
>>> pypandoc.convert("https://whatever.org/text - whatever", to='md', format="html")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/js/external/pypandoc/pypandoc/__init__.py", line 69, in convert
    outputfile=outputfile, filters=filters)
  File "/home/js/external/pypandoc/pypandoc/__init__.py", line 325, in _convert_input
    'Pandoc died with exitcode "%s" during conversion: %s' % (p.returncode, stderr)
RuntimeError: Pandoc died with exitcode "1" during conversion: b'pandoc: https://whatever.org/text - whatever: openFile: does not exist (No such file or directory)\n'
>>> pypandoc.convert_text("https://whatever.org/text - whatever", to='md', format="html")
'https://whatever.org/text - whatever\n'
>>> 
```

**Comment by matejzero** [comment]
Oooo I'm sorry, I totally missed that.

Thanks.
