### ISSUE TITLE
tests fail with 

### ISSUE THREAD

**Issue by keszybz** [bebraw/pypandoc#149]
[Another Fedora maintainer here]

I'm trying to build pypandoc with pandoc-2.0.6-1.fc28.x86_64, and unfortunately there are many test failures:
```
+ /usr/bin/python2 tests.py
test_basic_conversion_from_file (__main__.TestPypandoc) ... FAIL
test_basic_conversion_from_file_url (__main__.TestPypandoc) ... ok
test_basic_conversion_from_file_with_format (__main__.TestPypandoc) ... FAIL
test_basic_conversion_from_http_url (__main__.TestPypandoc) ... ERROR
test_basic_conversion_from_string (__main__.TestPypandoc) ... FAIL
test_basic_conversion_to_file (__main__.TestPypandoc) ... FAIL
test_call_with_nonexisting_file (__main__.TestPypandoc) ... ok
test_conversion_error (__main__.TestPypandoc) ... ok
test_conversion_from_markdown_with_extensions (__main__.TestPypandoc) ... FAIL
test_conversion_from_non_plain_text_file (__main__.TestPypandoc) ... FAIL
test_conversion_with_citeproc_filter (__main__.TestPypandoc) ... ok
test_conversion_with_empty_filter (__main__.TestPypandoc) ... ok
test_conversion_with_markdown_extensions (__main__.TestPypandoc) ... ok
test_convert_text_with_existing_file (__main__.TestPypandoc) ... ok
test_convert_with_custom_writer (__main__.TestPypandoc) ... ERROR
test_converts_valid_format (__main__.TestPypandoc) ... ok
test_depreaction_warnings (__main__.TestPypandoc) ... ok
test_does_not_convert_from_invalid_format (__main__.TestPypandoc) ... ok
test_does_not_convert_to_invalid_format (__main__.TestPypandoc) ... ok
test_get_pandoc_formats (__main__.TestPypandoc) ... ok
test_get_pandoc_path (__main__.TestPypandoc) ... ok
test_get_pandoc_version (__main__.TestPypandoc) ... FAIL
test_pdf_conversion (__main__.TestPypandoc) ... ok
test_unicode_input (__main__.TestPypandoc) ... ok

======================================================================
ERROR: test_basic_conversion_from_http_url (__main__.TestPypandoc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 174, in test_basic_conversion_from_http_url
    received = pypandoc.convert(url, 'html')
  File "/builddir/build/BUILD/pypandoc-1.4/pypandoc/__init__.py", line 69, in convert
    outputfile=outputfile, filters=filters)
  File "/builddir/build/BUILD/pypandoc-1.4/pypandoc/__init__.py", line 325, in _convert_input
    'Pandoc died with exitcode "%s" during conversion: %s' % (p.returncode, stderr)
RuntimeError: Pandoc died with exitcode "61" during conversion: Could not fetch https://raw.githubusercontent.com/bebraw/pypandoc/master/README.md
HttpExceptionRequest Request {
  host                 = "raw.githubusercontent.com"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/bebraw/pypandoc/master/README.md"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (ConnectionFailure Network.Socket.getAddrInfo: does not exist (Name or service not known))


======================================================================
ERROR: test_convert_with_custom_writer (__main__.TestPypandoc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 186, in test_convert_with_custom_writer
    received = pypandoc.convert_file(file_name, lua_file_name)
  File "/builddir/build/BUILD/pypandoc-1.4/pypandoc/__init__.py", line 140, in convert_file
    outputfile=outputfile, filters=filters)
  File "/builddir/build/BUILD/pypandoc-1.4/pypandoc/__init__.py", line 325, in _convert_input
    'Pandoc died with exitcode "%s" during conversion: %s' % (p.returncode, stderr)
RuntimeError: Pandoc died with exitcode "1" during conversion: pandoc: /tmp/tmpgzhgxsfoo-bar+baz/tmpla1sgh.lua: openFile: does not exist (No such file or directory)


======================================================================
FAIL: test_basic_conversion_from_file (__main__.TestPypandoc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 156, in test_basic_conversion_from_file
    self.assertEqualExceptForNewlineEnd(expected, received)
  File "tests.py", line 403, in assertEqualExceptForNewlineEnd
    self.assertEqual(expected.rstrip('\n'), received.rstrip('\n'))
AssertionError: u'some title\n==========' != u'#some title'
- some title
?           -
+ #some title? +
- ==========

======================================================================
FAIL: test_basic_conversion_from_file_with_format (__main__.TestPypandoc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 193, in test_basic_conversion_from_file_with_format
    self.assertEqualExceptForNewlineEnd(expected, received)
  File "tests.py", line 403, in assertEqualExceptForNewlineEnd
    self.assertEqual(expected.rstrip('\n'), received.rstrip('\n'))
AssertionError: u'some title\n==========' != u'#some title'
- some title
?           -
+ #some title? +
- ==========

======================================================================
FAIL: test_basic_conversion_from_string (__main__.TestPypandoc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 201, in test_basic_conversion_from_string
    self.assertEqualExceptForNewlineEnd(expected, received)
  File "tests.py", line 403, in assertEqualExceptForNewlineEnd
    self.assertEqual(expected.rstrip('\n'), received.rstrip('\n'))
AssertionError: u'some title\n==========' != u'#some title'
- some title
?           -
+ #some title? +
- ==========

======================================================================
FAIL: test_basic_conversion_to_file (__main__.TestPypandoc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 235, in test_basic_conversion_to_file
    self.assertEqualExceptForNewlineEnd(expected, written)
  File "tests.py", line 403, in assertEqualExceptForNewlineEnd
    self.assertEqual(expected.rstrip('\n'), received.rstrip('\n'))
AssertionError: u'some title\n==========' != u'#some title'
- some title
?           -
+ #some title? +
- ==========

======================================================================
FAIL: test_conversion_from_markdown_with_extensions (__main__.TestPypandoc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 226, in test_conversion_from_markdown_with_extensions
    self.assertEqualExceptForNewlineEnd(expected_without_extension, received_without_extension)
  File "tests.py", line 403, in assertEqualExceptForNewlineEnd
    self.assertEqual(expected.rstrip('\n'), received.rstrip('\n'))
AssertionError: u'<p><sub><sub>strike</sub></sub></p>' != u'<p>~<sub>strike</sub>~</p>'
- <p><sub><sub>strike</sub></sub></p>
?    ^^^^^                 ^^^^^^
+ <p>~<sub>strike</sub>~</p>
?    ^                 ^


======================================================================
FAIL: test_conversion_from_non_plain_text_file (__main__.TestPypandoc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 323, in test_conversion_from_non_plain_text_file
    self.assertEqualExceptForNewlineEnd(expected, received)
  File "tests.py", line 403, in assertEqualExceptForNewlineEnd
    self.assertEqual(expected.rstrip('\n'), received.rstrip('\n'))
AssertionError: u'some title\n==========' != u'#some title'
- some title
?           -
+ #some title? +
- ==========

======================================================================
/builddir
/builddir
/builddir
/builddir
/builddir
/builddir
/builddir
/builddir
/builddir
/builddir
/builddir
/builddir
/builddir
/builddir
/builddir
/builddir
/builddir
/builddir
/builddir
/builddir
/builddir
/builddir
/builddir
/builddir
FAIL: test_get_pandoc_version (__main__.TestPypandoc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 137, in test_get_pandoc_version
    self.assertTrue(major in [0, 1])
AssertionError: False is not true

----------------------------------------------------------------------
Ran 24 tests in 15.428s

FAILED (failures=7, errors=2)
```
As I mentioned in #124, with pandoc-1.19.1-3.fc27.x86_64, the only thing that fails is `test_basic_conversion_from_http_url`.

Are there any plans to support pandoc 2?

**Comment by jankatins** [comment]
My guess is that most of teh failures are due to pandoc not accepting '#title' anymore but only '# title' (space between '#' and text). pandoc 2 should be supported by simply adding the new version in there, that was a sanity check which is now simply wrong :-(.

**Comment by jankatins** [comment]
in #156 I've added some workarounds for the uppercase tempfile and also added a upstream bug in pandoc.
