### ISSUE TITLE
Pandoc died with exitcode "47"

### ISSUE THREAD

**Issue by starhh** [bebraw/pypandoc#152]
Hi,
I am following the documentation to convert md file to pdf using below code, I am using python 3.6 on windows. I encounter below error to select a different --pdf-engine or install pdflatex\r\n'.

I do not want to install other dependency, Please assist. Thanks

output = pypandoc.convert(input, 'pdf', outputfile='paper.pdf', extra_args=['-V geometry:margin=1.5cm'])

Traceback (most recent call last):
  File "C:/Users/star/Desktop/pdf_report/pypan.py", line 16, in <module>
    output = pypandoc.convert(input, 'pdf', outputfile='demo.pdf')
  File "C:\Users\star\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pypandoc\__init__.py", line 69, in convert
    outputfile=outputfile, filters=filters)
  File "C:\Users\star\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pypandoc\__init__.py", line 325, in _convert_input
    'Pandoc died with exitcode "%s" during conversion: %s' % (p.returncode, stderr)
RuntimeError: Pandoc died with exitcode "47" during conversion: b'pdflatex not found. Please select a different --pdf-engine or install pdflatex\r\n'

**Comment by starhh** [comment]
Also I tried with paramter --pdf-engine=xelatex'

output = pypandoc.convert(input, 'pdf', outputfile='paper.pdf', extra_args=['-V geometry:margin=1.5cm', '--pdf-engine=xelatex'])

https://pandoc.org/MANUAL.html#creating-a-pdf

**Comment by GeoSpark** [comment]
You need to separate the parameters, so:
`extra_args=['-V geometry:margin=1.5cm', '--pdf-engine=/usr/bin/xelatex']`
becomes:
`extra_args=['-V', 'geometry:margin=1.5cm', '--pdf-engine', '/usr/bin/xelatex']`

**Comment by ylz-at** [comment]
I am using downlaod_pandoc(), but there is no method provided to download pdf-engine.
`Pandoc died with exitcode "41" during conversion: pandoc: pdflatex not found. pdflatex is needed for pdf output.`
