### ISSUE TITLE
Failure to install on 2.7 due to Unicode in metadata

### ISSUE THREAD

**Issue by arcivanov** [bebraw/pypandoc#153]
```  
Updating cache with response from "https://pypi.python.org/packages/71/81/00184643e5a10a456b4118fc12c96780823adb8ed974eb2289f29703b29b/pypandoc-1.4.tar.gz"
  Caching due to etag
  Running setup.py (path:/tmp/pip-build-NLObzp/pypandoc/setup.py) egg_info for package pypandoc
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/pypandoc.egg-info
    writing requirements to pip-egg-info/pypandoc.egg-info/requires.txt
    writing pip-egg-info/pypandoc.egg-info/PKG-INFO
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-NLObzp/pypandoc/setup.py", line 116, in <module>
        cmdclass=cmd_classes
      File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/opt/python/2.7.14/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/opt/python/2.7.14/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/opt/python/2.7.14/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 271, in run
        writer(self, ep.name, os.path.join(self.egg_info, ep.name))
      File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 604, in write_pkg_info
        metadata.write_pkg_info(cmd.egg_info)
      File "/opt/python/2.7.14/lib/python2.7/distutils/dist.py", line 1106, in write_pkg_info
        self.write_pkg_file(pkg_info)
      File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/setuptools/dist.py", line 76, in write_pkg_file
        file.write('%s: %s\n' % (field, attr_val))
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 17: ordinal not in range(128)
Cleaning up...
Exception information:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-NLObzp/pypandoc/
```

**Comment by jankatins** [comment]
I tried to workaround in https://github.com/bebraw/pypandoc/pull/156

**Comment by jankatins** [comment]
Can you test with the latest master?

**Comment by jankatins** [comment]
No response, closing
