### ISSUE TITLE
Test failures with pandoc 2.2.1

### ISSUE THREAD

**Issue by felixonmars** [bebraw/pypandoc#163]
```
======================================================================
FAIL: test_basic_conversion_from_file (tests.TestPypandoc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-pypandoc/src/pypandoc-1.4/tests.py", line 156, in test_basic_conversion_from_file
    self.assertEqualExceptForNewlineEnd(expected, received)
  File "/build/python-pypandoc/src/pypandoc-1.4/tests.py", line 398, in assertEqualExceptForNewlineEnd
    self.assertEqual(expected.rstrip('\n'), received.rstrip('\n'))
AssertionError: 'some title\n==========' != '#some title'
- some title
?           -
+ #some title? +
- ==========

======================================================================
FAIL: test_basic_conversion_from_file_with_format (tests.TestPypandoc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-pypandoc/src/pypandoc-1.4/tests.py", line 188, in test_basic_conversion_from_file_with_format
    self.assertEqualExceptForNewlineEnd(expected, received)
  File "/build/python-pypandoc/src/pypandoc-1.4/tests.py", line 398, in assertEqualExceptForNewlineEnd
    self.assertEqual(expected.rstrip('\n'), received.rstrip('\n'))
AssertionError: 'some title\n==========' != '#some title'
- some title
?           -
+ #some title? +
- ==========

======================================================================
FAIL: test_basic_conversion_from_string (tests.TestPypandoc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-pypandoc/src/pypandoc-1.4/tests.py", line 196, in test_basic_conversion_from_string
    self.assertEqualExceptForNewlineEnd(expected, received)
  File "/build/python-pypandoc/src/pypandoc-1.4/tests.py", line 398, in assertEqualExceptForNewlineEnd
    self.assertEqual(expected.rstrip('\n'), received.rstrip('\n'))
AssertionError: 'some title\n==========' != '#some title'
- some title
?           -
+ #some title? +
- ==========

======================================================================
FAIL: test_basic_conversion_to_file (tests.TestPypandoc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-pypandoc/src/pypandoc-1.4/tests.py", line 230, in test_basic_conversion_to_file
    self.assertEqualExceptForNewlineEnd(expected, written)
  File "/build/python-pypandoc/src/pypandoc-1.4/tests.py", line 398, in assertEqualExceptForNewlineEnd
    self.assertEqual(expected.rstrip('\n'), received.rstrip('\n'))
AssertionError: 'some title\n==========' != '#some title'
- some title
?           -
+ #some title? +
- ==========

======================================================================
FAIL: test_conversion_from_markdown_with_extensions (tests.TestPypandoc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-pypandoc/src/pypandoc-1.4/tests.py", line 221, in test_conversion_from_markdown_with_extensions
    self.assertEqualExceptForNewlineEnd(expected_without_extension, received_without_extension)
  File "/build/python-pypandoc/src/pypandoc-1.4/tests.py", line 398, in assertEqualExceptForNewlineEnd
    self.assertEqual(expected.rstrip('\n'), received.rstrip('\n'))
AssertionError: '<p><sub><sub>strike</sub></sub></p>' != '<p>~<sub>strike</sub>~</p>'
- <p><sub><sub>strike</sub></sub></p>
?    ^^^^^                 ^^^^^^
+ <p>~<sub>strike</sub>~</p>
?    ^                 ^


======================================================================
FAIL: test_conversion_from_non_plain_text_file (tests.TestPypandoc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-pypandoc/src/pypandoc-1.4/tests.py", line 318, in test_conversion_from_non_plain_text_file
    self.assertEqualExceptForNewlineEnd(expected, received)
  File "/build/python-pypandoc/src/pypandoc-1.4/tests.py", line 398, in assertEqualExceptForNewlineEnd
    self.assertEqual(expected.rstrip('\n'), received.rstrip('\n'))
AssertionError: 'some title\n==========' != '#some title'
- some title
?           -
+ #some title? +
- ==========

======================================================================
FAIL: test_convert_with_custom_writer (tests.TestPypandoc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-pypandoc/src/pypandoc-1.4/tests.py", line 182, in test_convert_with_custom_writer
    self.assertEqualExceptForNewlineEnd(expected, received)
  File "/build/python-pypandoc/src/pypandoc-1.4/tests.py", line 398, in assertEqualExceptForNewlineEnd
    self.assertEqual(expected.rstrip('\n'), received.rstrip('\n'))
AssertionError: '<h1 id="title">title</h1>' != '<p>#title</p>'
- <h1 id="title">title</h1>
+ <p>#title</p>


======================================================================
FAIL: test_get_pandoc_version (tests.TestPypandoc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-pypandoc/src/pypandoc-1.4/tests.py", line 137, in test_get_pandoc_version
    self.assertTrue(major in [0, 1])
AssertionError: False is not true

----------------------------------------------------------------------
Ran 24 tests in 11.015s

FAILED (failures=8)
```

**Comment by jankatins** [comment]
Fix is merged
