### ISSUE TITLE
pandoc fails with "invalid argument (invalid character)"

### ISSUE THREAD

**Issue by voigt** [bebraw/pypandoc#56]
Hey,

unfortunately pandoc seem to fail with the following string:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import pypandoc as pandoc

markdown = '''This is a test

&#55357; &#56862;'''

html = pandoc.convert(markdown, 'html', format='md')
```

This is the error message:

```
$ python test.py 
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    html = pandoc.convert(markdown, 'html', format='md')
  File "/Library/Python/2.7/site-packages/pypandoc.py", line 94, in convert
    outputfile=outputfile, filters=filters)
  File "/Library/Python/2.7/site-packages/pypandoc.py", line 135, in _convert
    filters=filters)
  File "/Library/Python/2.7/site-packages/pypandoc.py", line 204, in _process_file
    'Pandoc died with exitcode "%s" during conversation: %s' % (p.returncode, stderr)
RuntimeError: Pandoc died with exitcode "1" during conversation: pandoc: <stdout>: commitBuffer: invalid argument (invalid character)
```

I am using pandoc version `1.14.0.1` and pypandoc `0.9.7`. Interestingly the same script works with Ubuntu 14.04 (Python 2.7.5) like a charme, but fails with OSX 10.9.5 (Python 2.7.5).

I assume its some kind of encoding issue but have no idea how to fix this?

Kind regards,
Christoph

**Comment by bebraw** [comment]
@voigt I can reproduce the issue on my system. It looks like Pandoc chokes on that entity. Demo:

```bash
pandoc --from=markdown --to=html demo.md
<p>pandoc: <stdout>: commitBuffer: invalid argument (invalid character)
```

**demo.md**

```markdown
&#55357;
```

So it seems to me it's something pandoc related. Perhaps we should escalate the issue and ask the pandoc guys?

**Comment by bebraw** [comment]
@voigt Did you have time to investigate this further?

**Comment by bebraw** [comment]
Closing due to inactivity. Feel free to open again if you bump into it. Quite a bit has happened in the package since.
