### ISSUE TITLE
pypandoc.convert() doesn't handle errors properly

### ISSUE THREAD

**Issue by marbu** [bebraw/pypandoc#86]
Function `pypandoc.convert()` doesn't handle errors properly.

When I call `pypandoc.convert(filepath, 'rst')` with filepath which doesn't
exists, I got puzzling exception `RuntimeError: Missing format!` insdead of
statement of actual root cause of the error.

Similar issue happen when an empty string or int is passed as a filepath.

## Reproducer

Here is simple reproducer:

```
#!/usr/bin/env python
# -*- coding: utf8 -*-


import traceback
import sys

import pypandoc


files = [
    '/home/martin/projects/pyp2rpm/README.md',
    '/home/martin/projects/pypandoc/README.md',
    '/home/martin/tmp/doesnotexists.md',
    '',
    42,
    None,
    ]

for filepath in files:
    print("converting '{0}' (type: {1})".format(filepath, type(filepath)))
    try:
        pypandoc.convert(filepath, 'rst')
    except Exception:
        traceback.print_exc(file=sys.stdout)
    print()
```

When I run this script on my machine where 1st two files exists, I got
the following output:

```
$ ./reproducer.py
converting '/home/martin/projects/pyp2rpm/README.md' (type: <class 'str'>)

converting '/home/martin/projects/pypandoc/README.md' (type: <class 'str'>)

converting '/home/martin/tmp/doesnotexists.md' (type: <class 'str'>)
Traceback (most recent call last):
  File "./reproducer.py", line 23, in <module>
    pypandoc.convert(filepath, 'rst')
  File "/home/martin/projects/pypandoc/.env/lib/python3.4/site-packages/pypandoc-1.1.2-py3.4.egg/pypandoc/__init__.py", line 50, in convert
    outputfile=outputfile, filters=filters)
  File "/home/martin/projects/pypandoc/.env/lib/python3.4/site-packages/pypandoc-1.1.2-py3.4.egg/pypandoc/__init__.py", line 68, in _convert
    raise RuntimeError('Missing format!')
RuntimeError: Missing format!

converting '' (type: <class 'str'>)
Traceback (most recent call last):
  File "./reproducer.py", line 23, in <module>
    pypandoc.convert(filepath, 'rst')
  File "/home/martin/projects/pypandoc/.env/lib/python3.4/site-packages/pypandoc-1.1.2-py3.4.egg/pypandoc/__init__.py", line 50, in convert
    outputfile=outputfile, filters=filters)
  File "/home/martin/projects/pypandoc/.env/lib/python3.4/site-packages/pypandoc-1.1.2-py3.4.egg/pypandoc/__init__.py", line 68, in _convert
    raise RuntimeError('Missing format!')
RuntimeError: Missing format!

converting '42' (type: <class 'int'>)
Traceback (most recent call last):
  File "./reproducer.py", line 23, in <module>
    pypandoc.convert(filepath, 'rst')
  File "/home/martin/projects/pypandoc/.env/lib/python3.4/site-packages/pypandoc-1.1.2-py3.4.egg/pypandoc/__init__.py", line 50, in convert
    outputfile=outputfile, filters=filters)
  File "/home/martin/projects/pypandoc/.env/lib/python3.4/site-packages/pypandoc-1.1.2-py3.4.egg/pypandoc/__init__.py", line 68, in _convert
    raise RuntimeError('Missing format!')
RuntimeError: Missing format!

converting 'None' (type: <class 'NoneType'>)
Traceback (most recent call last):
  File "./reproducer.py", line 23, in <module>
    pypandoc.convert(filepath, 'rst')
  File "/home/martin/projects/pypandoc/.env/lib/python3.4/site-packages/pypandoc-1.1.2-py3.4.egg/pypandoc/__init__.py", line 50, in convert
    outputfile=outputfile, filters=filters)
  File "/home/martin/projects/pypandoc/.env/lib/python3.4/site-packages/pypandoc-1.1.2-py3.4.egg/pypandoc/__init__.py", line 55, in _convert
    source, format, input_type = reader(source, format, encoding=encoding)
  File "/home/martin/projects/pypandoc/.env/lib/python3.4/site-packages/pypandoc-1.1.2-py3.4.egg/pypandoc/__init__.py", line 96, in _read_file
    path = os.path.exists(source)
  File "/home/martin/projects/pypandoc/.env/lib/python3.4/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: can't specify None for path argument
```

**Comment by bebraw** [comment]
Great point. Do you want to PR?

**Comment by marbu** [comment]
Oh, why not, I will try to suggest a fix in a pull request.

**Comment by marbu** [comment]
@bebraw looking at the code, it seems that you check if `source` parameter matches some file in a filesystem and based on that, the variable is handled either as filepath or actual content. I don't think I can do a quick patch without breaking the api. Btw why is `_convert()` function wrapped like that? Whouldn't be easier and more readable to use the function directly?

**Comment by JanSchulz** [comment]
IMO there are two possible solutions:

* introduce two additional functions `convert_file()` and `convert_string()` and soft-deprecate the old convert function.
* try to get a basedir of the input and if that exists (or simple check if it is file like: contains a path separator or ends in a known extension), raise an error "input appears to be a filepath but the actual file doe snot exist".

I'm actually in favor of the first solution...

@bebraw I've also wondered about the indirect call of the real converter :-) Is that only done for the tests?

**Comment by bebraw** [comment]
> introduce two additional functions convert_file() and convert_string() and soft-deprecate the old convert function.

:+1:

> @bebraw I've also wondered about the indirect call of the real converter :-) Is that only done for the tests?

That's possible. Maybe it's some legacy bit that could be removed.

**Comment by bebraw** [comment]
We need to resolve this somehow. Does someone want to give it a go?

**Comment by janschulz** [comment]
This is now taken care of in #96
