### ISSUE TITLE
Build on py3.5 fails

### ISSUE THREAD

**Issue by JanSchulz** [bebraw/pypandoc#90]
```
$ obvci_conda_build_dir ./recipes janschulz --channel main --build-condition "python >=3.5,<3.6"
Fetching package metadata: ......
Resolving distributions from 5 recipes... 
Computed that there are 4 distributions from the 5 recipes:
Resolved dependencies, will be built in the following order: 
	matplotlib-1.5.0+532.g3d942f7.dirty-py35_0 (will be built: False)
	pypandoc-1.1.3-py35_0 (will be built: True)
	statsmodels-0.6.1-py35_0 (will be built: True)
	ipyext-0.1.0-py35_0 (will be built: False)
Nothing to be done for matplotlib - it is already on main.
Building  pypandoc-1.1.3-py35_0
Removing old build environment
Removing old work directory
BUILD START: pypandoc-1.1.3-py35_0
Fetching package metadata: ........
Solving package specifications: ..........
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    python-3.5.1               |                0        12.7 MB  defaults
    setuptools-19.2            |           py35_0         349 KB  defaults
    wheel-0.26.0               |           py35_1          77 KB  defaults
    pip-7.1.2                  |           py35_0         1.4 MB  defaults
    ------------------------------------------------------------
                                           Total:        14.6 MB
The following NEW packages will be INSTALLED:
    openssl:    1.0.2e-0      defaults
    pip:        7.1.2-py35_0  defaults
    python:     3.5.1-0       defaults
    readline:   6.2-2         defaults
    setuptools: 19.2-py35_0   defaults
    sqlite:     3.9.2-0       defaults
    tk:         8.5.18-0      defaults
    wheel:      0.26.0-py35_1 defaults
    xz:         5.0.5-0       defaults
    zlib:       1.2.8-0       defaults
Removing old work directory
checkout: u'v1.1.3'
==> git log -n1 <==
commit 7f03f316f2015fd8254fb2387681008f2b597444
Author: Jan Schulz <jasc@gmx.net>
Date:   Fri Jan 15 21:27:17 2016 +0100
    pypandoc v1.1.3
==> git describe --tags --dirty <==
v1.1.3
==> git status <==
HEAD detached at v1.1.3
nothing to commit, working directory clean
Package: pypandoc-1.1.3-py35_0
source tree in: /Users/travis/miniconda/conda-bld/work
+ /Users/travis/miniconda/envs/_build/bin/python setup.py download_pandoc
Maybe try:
    brew install pandoc
See http://johnmacfarlane.net/pandoc/installing.html
for installation options
---------------------------------------------------------------
!!! pandoc not found, long_description is bad, don't upload this to PyPI !!!
running download_pandoc
* Downloading pandoc from https://github.com/jgm/pandoc/releases/download/1.15.1/pandoc-1.15.1-osx.pkg ...
* Unpacking pandoc-1.15.1-osx.pkg to tempfolder...
x .
x ./usr
x ./usr/local
x ./usr/local/bin
x ./usr/local/bin/pandoc
x ./usr/local/bin/pandoc-citeproc
x ./usr/local/share
x ./usr/local/share/man
x ./usr/local/share/man/man1
x ./usr/local/share/man/man1/pandoc-citeproc.1
x ./usr/local/share/man/man1/pandoc.1
x ./usr/local/share/man/man5
* Copying pandoc to /Users/travis/miniconda/conda-bld/work/pypandoc/files ...
* Copying pandoc-citeproc to /Users/travis/miniconda/conda-bld/work/pypandoc/files ...
* Done.
++ uname -s
+ '[' Darwin '!=' Linux ']'
+ echo 'Build wheels...'
Build wheels...
+ /Users/travis/miniconda/envs/_build/bin/python setup.py bdist_wheel
Maybe try:
    brew install pandoc
See http://johnmacfarlane.net/pandoc/installing.html
for installation options
---------------------------------------------------------------
!!! pandoc not found, long_description is bad, don't upload this to PyPI !!!
Patching wheel building...
Making sure that wheel is platform specific...
running bdist_wheel
Traceback (most recent call last):
  File "setup.py", line 238, in <module>
    cmdclass=cmd_classes
  File "/Users/travis/miniconda/envs/_build/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/travis/miniconda/envs/_build/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/travis/miniconda/envs/_build/lib/python3.5/distutils/dist.py", line 973, in run_command
    cmd_obj.ensure_finalized()
  File "/Users/travis/miniconda/envs/_build/lib/python3.5/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 210, in finalize_options
    assert "any" not in self.get_archive_basename(), "bdist_wheel will not generate platform specific names, aborting!"
  File "/Users/travis/miniconda/envs/_build/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 162, in get_archive_basename
    impl_tag, abi_tag, plat_tag = self.get_tag()
  File "setup.py", line 206, in get_tag
    assert tag == supported_tags[0]
AssertionError
Command failed: /bin/bash -x -e /Users/travis/build/JanSchulz/package-builder/recipes/pypandoc/build.sh
The command "obvci_conda_build_dir ./recipes janschulz --channel main --build-condition "python >=3.5,<3.6"" exited with 1.
```

Will probably be fixed by https://github.com/bebraw/pypandoc/issues/84

**Comment by JanSchulz** [comment]
And windows as well:https://ci.appveyor.com/project/JanSchulz/package-builder/build/job/f0jb9l9j35ic6yq6

```
...
pip install twine
Collecting twine 
  Downloading twine-1.6.5-py2.py3-none-any.whl 
Collecting pkginfo>=1.0 (from twine) 
  Downloading pkginfo-1.2.1.tar.gz 
Collecting requests-toolbelt>=0.4.0 (from twine) 
  Downloading requests_toolbelt-0.5.1-py2.py3-none-any.whl (55kB) 
Requirement already satisfied (use --upgrade to upgrade): requests>=2.3.0 in c:\conda\lib\site-packages (from twine) 
Requirement already satisfied (use --upgrade to upgrade): setuptools>=0.7.0 in c:\conda\lib\site-packages\setuptools-19.2-py3.5.egg (from twine)
Building wheels for collected packages: pkginfo
  Running setup.py bdist_wheel for pkginfo 
  Stored in directory: C:\Users\appveyor\AppData\Local\pip\Cache\wheels\8e\c7\e9\a770012d679a6ed6831354e4982e5d3b942fb6666d70d3342b 
Successfully built pkginfo 
Installing collected packages: pkginfo, requests-toolbelt, twine
Successfully installed pkginfo-1.2.1 requests-toolbelt-0.5.1 twine-1.6.5 
rmdir /Q /S c:\cygwin
%CMD_IN_ENV% obvci_conda_build_dir recipes janschulz --channel main  --build-condition "%PY_CONDITION%"
Using default MSVC build environment for 64 bit architecture
Executing: obvci_conda_build_dir recipes janschulz --channel main  --build-condition "python >=3.5,<3.6"
Fetching package metadata: ...... 
Resolving distributions from 6 recipes... 
Computed that there are 5 distributions from the 6 recipes:
Resolved dependencies, will be built in the following order: 
	msinttypes-r26-0 (will be built: False)
	pypandoc-1.1.3-py35_0 (will be built: False)
	statsmodels-0.6.1-py35_0 (will be built: True)
	ipyext-0.1.0-py35_0 (will be built: False)
	matplotlib-1.5.0+532.g3d942f7.dirty-py35_0 (will be built: False) 
Nothing to be done for msinttypes - it is already on main.
Nothing to be done for pypandoc - it is already on main.
Building  statsmodels-0.6.1-py35_0
Removing old build environment
Removing old work directory
BUILD START: statsmodels-0.6.1-py35_0
Fetching package metadata: ........ 
Solving package specifications: .................. 
Error: Unsatisfiable package specifications.
Generating hint: 
[                    ]|                                                  |   0%
[4/7                 ]|############################                      |  57%
[5/7                 ]|###################################               |  71%
[      COMPLETE      ]|##################################################| 100%
 
 
Hint: the following packages conflict with each other:
  - python 3.5*
  - distribute
 
Use 'conda info python' etc. to see the dependencies for each package.
 
Note that the following features are enabled:
  - vc14
 
Command exited with code 1
```

**Comment by JanSchulz** [comment]
Windows is a packaging error... but the osx one should be fixed with the new workaround as part of #92

**Comment by ssbarnea** [comment]
Still broken on Mac Python 3.5 (works with 2.7)
```
      assert "any" not in self.get_archive_basename(), "bdist_wheel will not generate platform specific names, aborting!"
    File "/usr/local/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 162, in get_archive_basename
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/private/var/folders/5s/866_p9c16k59ygvyqnkmpv000000gn/T/pip-build-wthsaogt/pypandoc/setup.py", line 206, in get_tag
      assert tag == supported_tags[0]
  AssertionError
```

**Comment by ssbarnea** [comment]
I was able to bypass this error by adding these requirements:
```
pip>8.1.0
wheel>0.25.0
```

**Comment by bebraw** [comment]
@JanSchulz Would those requirements work for you? Can you see any potential issues?
